### PR TITLE
skipped files newer than 1 hour to prevent glance store false alarms

### PR DESCRIPTION
**Pull request by nealbrown**
Per https://github.com/blueboxgroup/ursula-monitoring/issues/43

This will provide an hour window for the glance stores to sync, which given my understanding of the issue is sufficient to prevent false alarms.

### CODE REVIEW

**Comment by omgjlk** [comment]
So I'm not sure this is right. This check you've modified is for unknown files. That'd be files that exist on the filesystem but don't have a glance entry. New files would have the glance entry. I thought the issue we were trying to solve was when there is an entry in glance but the file hasn't shown up yet. @ulyssesbbg can you chime in ?

**Comment by nealbrown** [comment]
Ok I matched the error message that was cited in the issue, we can certainly do it for the other cases.

**Comment by ulyssesbbg** [comment]
@j2sol Can we expand to 2 or 3 hours?  Sometimes the images are pretty big or there are a whole bunch of them coming in at once.

**Comment by ulyssesbbg** [comment]
Also we want to ignore new images for alerts like "Glance image 11ee284e-9150-417f-b2a9-b1442e232d0b size differs from file on disk" - this is because they're syncing - Neal says he'll fix that tomorrow.

**Comment by nealbrown** [comment]
Ok will update for above case and also increase ignore time to 12 hours per craig

**Pull request closed without merging**
