### PR TITLE
Fixes for storcli detection in RAID check

### PR DESCRIPTION
**Pull request by jyotty**
- Pulls in a fix for check-storcli.pl from upstream (would previously blow any config away and look for _only_ `storcli64` in your `$PATH`, and fail otherwise). Requires installation of `libfile-which-perl` package.
- Better "is storcli installed?" test for invoking check-storcli.pl. (Depending on which version of the package is installed, the executable could be either `storcli` or `storcli64`.)

### CODE REVIEW

**Comment by scoop206** [comment]
@jyotty can you test this by hand ( since jenkins doesn't do ursula-monitoring testing ).

**Comment by omgjlk** [comment]
:+1: Awaiting manual testing results.

**Comment by jyotty** [comment]
This works with either the tkraid storcli package or the alien-converted RPM from LSI.

**Comment by omgjlk** [comment]
Is there a PR in Ursula to pull in libfile-which-perl ?

**Comment by omgjlk** [comment]
Just thinking. The ursula side got merged, but we've got older installs that are set to use master for ursula-monitoring. Is there any way we can protect against a usage error if the module isn't available on those hosts? (yes, pulling from master always might not be the best of ideas).

**Comment by jyotty** [comment]
I can [fatpack](http://search.cpan.org/perldoc?App::FatPacker) the dependency into the file trivially. But I'd rather get the module installed normally.

**Comment by omgjlk** [comment]
Okay, so to make all 1.2.x hosts work with monitoring, I've done
https://github.com/blueboxgroup/ursula/pull/1030 to backport the package
install. Once that goes in, we can merge this.
- jlk

**Comment by masteinhauser** [comment]
So, looks like PR https://github.com/blueboxgroup/ursula/pull/1030 has been merged, should this be merge-able now?

**Pull request closed without merging**
