### PR TITLE
Make nearfull osd a critical alert

### PR DESCRIPTION
**Pull request by knandya**
@ulyssesbbg @j2sol  @paulczar  Adding additional check to make nearfull osd a Critical alert.

### CODE REVIEW

**Comment by omgjlk** [comment]
Can you explain, perhaps in the commit message itself, why this is necessary instead of setting the mon_osd_full_ratio to a lower number? If both near full and full are critical, why have a distinction between the two?

**Comment by knandya** [comment]
When a OSD reaches full ratio, all I/O to the cluster is going to blocked.  That is the reason ceph has nearfull ratio setting, which gives operator to plan for scale-out or manage the disk utilization. When a osd reaches nearfull ratio, the I/O is not blocked. Just cluster status changes to HEALTH_WARN from HEALTH_OK. So, having a lower full ratio is going to block the I/O too early and it will be too late to plan for scale-out.

In general, nearfull ratio is a Warning alert. As Ops team requested it be Critical, to get better visibility for the alert. this code change is necessitated.

**Comment by omgjlk** [comment]
This is a common repo shared by not just us. Whether or not to make near full a critical alert, that seems more like a site decision, rather than something changed in code itself.

Is there a way we can make this configurable client-side?

**Comment by knandya** [comment]
I'm not sure of such option. @ulyssesbbg  any thoughts?

**Comment by paulczar** [comment]
something like:  `--nearfull-criticality=warning|critical`  ?

**Comment by ulyssesbbg** [comment]
Do we have internal documentation on all of the steps involved in updating a check like this to be Critical instead of Warning?

**Comment by omgjlk** [comment]
@ulyssesbbg Within ursula code we would define it as a critical, or make it a role default defined as a critical. Basically our objection is that a consumer of ursula-monitoring should make this decision, not ursula-monitoring code itself.

**Comment by paulczar** [comment]
I talked with Niraj about this yesterday,  turns out this check already has a criticality argument - https://github.com/knandya/ursula-monitoring/blob/28fc113b0530c2e56b59338343b816faa4ebdfd3/sensu/plugins/check-ceph.rb#L91-L95  so we should be able to update just that section to always respond as the criticality set in that argument.   something like :

```
    if result.start_with?('HEALTH_WARN')
       if result.include?('near full osd')
            if config[:criticality] == 'warning'
              warning result
            else
              critical result
            end
        end
  else

```

**Comment by knandya** [comment]
@paulczar @j2sol Made the change that Paul suggested.

**Comment by paulczar** [comment]
good enough for govt work :+1:

**Comment by omgjlk** [comment]
This still changes the check default. The check default used to be that a near full is a warning action. To make that part of it still be a warning you have to make nearly everything be a warning.

This isn't really any better than the first PR which just flat out made the near full status a critical alert.

That said, I'm kind of tired of arguing over this, and if we want to change the default, well then, okay...

**Comment by omgjlk** [comment]
Merging for now, but I think we can make this better in the future.

**Pull request merged**
